### ISSUE TITLE
Crash on initialize

### ISSUE THREAD

**Issue by Hamdaaa91** [qonversion/android-sdk#13]
I'm calling 
            Qonversion.initialize(application, BuildConfig.QONVERSION_KEY,  LoginModule.getInstance().userInfo.user.uid)

in Home activity, after the user got login as before that I will not have UID, but it gives me this crash
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/preference/PreferenceManager;
        at com.qonversion.android.sdk.Qonversion$Companion.initialize(Qonversion.kt:98)
        at com.qonversion.android.sdk.Qonversion$Companion.initialize(Qonversion.kt:48)
        at com.mindvalley.soulvana.home.HomeActivity.onCreate(HomeActivity.kt:164)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.preference.PreferenceManager" on path: DexPathList[[zip file "/data/app/com.mindvalley.soulvana-uEGzF4Kr7MC7x3xBoVeX8w==/base.apk"],nativeLibraryDirectories=[/data/app/com.mindvalley.soulvana-uEGzF4Kr7MC7x3xBoVeX8w==/lib/arm64, /data/app/com.mindvalley.soulvana-uEGzF4Kr7MC7x3xBoVeX8w==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.qonversion.android.sdk.Qonversion$Companion.initialize(Qonversion.kt:98) 
        at com.qonversion.android.sdk.Qonversion$Companion.initialize(Qonversion.kt:48) 
        at com.mindvalley.soulvana.home.HomeActivity.onCreate(HomeActivity.kt:164) 
        at android.app.Activity.performCreate(Activity.java:7825) 
        at android.app.Activity.performCreate(Activity.java:7814) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 

```

**Comment by ArtemyGlukhov** [comment]
Good afternoon. Thank you for contacting us. We will investigate the problem, and will return with the answer as soon as possible

**Comment by ArtemyGlukhov** [comment]
Hi! At first glance, it looks like you are trying to use SDK in a project without AndroidX support. Please make sure your project supports AndroidX. Check your gradle.properties flags 
android.useAndroidX, android.enableJetifier its values should be TRUE.
Make sure list of dependencies in your app build.gradle  contains dependencies such as "androidx ...." and does not contain dependencies of "com.android.support" at the same time
 
If your project supports AndroidX, then we need more information about the environment of your project, in particular the list of dependencies that your project uses.

**Comment by Hamdaaa91** [comment]
There was support library, updated it to its androidX version, but the issue still exists
Here's a list of dependencies

` com.google.firebase:firebase-core
  com.google.firebase:firebase-messaging
 com.google.firebase:firebase-database
com.google.firebase:firebase-config
com.google.firebase:firebase-analytics
com.google.firebase:firebase-perf
com.google.firebase:firebase-analytics
com.mindvalley.module_profile:module_profile "All updated to androidx"
com.mindvalley.module_login:Module_Login "All updated to androidx"
com.mindvalley.module_core:module_core "All updated to androidx"
com.mindvalley.module_analytics:module_analytics "All updated to androidx"
com.mindvalley.module_downloadmanager "All updated to androidx"
com.airbnb.android:lottie
androidx.multidex:multidex
androidx.appcompat:appcompat
com.android.billingclient:billing
com.apptimize:apptimize-android
com.facebook.android:facebook-applinks
com.crashlytics.sdk.android:crashlytics
androidx.lifecycle:lifecycle-extensions
androidx.lifecycle:lifecycle-runtime:
androidx.legacy:legacy-support-v4:1.0.0'
androidx.lifecycle:lifecycle-extensions:2.0.0'
androidx.lifecycle:lifecycle-viewmodel-ktx:2.0.0'
androidx.lifecycle:lifecycle-compiler:$rootConfiguration.archLifecycleVersion"
androidx.arch.core:core-testing:$rootConfiguration.archLifecycleVersion"
androidx.constraintlayout:constraintlayout:2.0.0-alpha4'


unit:junit:4.12
org.mockito:mockito-core
org.robolectric:robolectric
org.robolectric:shadows-multidex
androidx.test:runner:1.1.0

androidx.room:room-runtime
androidx.room:room-rxjava2
androidx.room:room-compiler
androidx.room:room-testing


com.google.dagger:dagger:
com.google.dagger:dagger-android:$daggerVer"
com.google.dagger:dagger-android-support:$daggerVer"
    kapt "com.google.dagger:dagger-compiler:$daggerVer"
    kapt "com.google.dagger:dagger-android-processor:$daggerVer"
     "com.squareup.retrofit2:adapter-rxjava2:$rxRetrofitAdapter"
     "io.reactivex.rxjava2:rxandroid:$rxAndroid"
     "io.reactivex.rxjava2:rxjava:$rxJava"
     "io.reactivex.rxjava2:rxkotlin:$rxkotlinVer"
     "com.facebook.stetho:stetho:$stethoVer"
     "com.facebook.stetho:stetho-okhttp3:$stethoVer"

     'com.jakewharton.timber:timber:4.7.1'

     'com.makeramen:roundedimageview:2.3.0'
     'com.zxy.android:tiny:1.1.0'
     'androidx.recyclerview:recyclerview:1.0.0'

   debug 'com.squareup.leakcanary:leakcanary-android:2.0-alpha-2'

     'com.google.android.material:material:1.0.0-rc01'

     'com.intuit.sdp:sdp-android:1.0.6'
     'de.hdodenhof:circleimageview:3.0.1'

     "com.ethanhua:skeleton:$skeletonVer"
     "io.supercharge:shimmerlayout:$shimmerVer"

     "org.kodein.di:kodein-di-generic-jvm:$kodienVer"
     "org.kodein.di:kodein-di-framework-android-x:$kodienVer"

     "com.google.android.material:material:$materialVer"

     'com.android.installreferrer:installreferrer:1.0'

    //Exoplayer
     "com.google.android.exoplayer:exoplayer-core:$exoplayerVer"
     "com.google.android.exoplayer:exoplayer-ui:$exoplayerVer"
     "com.google.android.exoplayer:exoplayer-hls:$exoplayerVer"

     "com.qonversion.android.sdk:sdk:0.2.2@aar"`

**Comment by ArtemyGlukhov** [comment]
Thank you for the information, I will try to reproduce the situation in order to understand better. And then I'll be back with the answer

**Comment by ArtemyGlukhov** [comment]
Hi, I'm try to reproduce your problem, and got same result. This is because you specified the conversion dependency incorrectly. The postfix @aar in the name of the artifact is superfluous, just remove it.
Correct dependency name is "com.qonversion.android.sdk:sdk:0.2.2"

**Comment by Hamdaaa91** [comment]
Removed it, it was mentioned in the documentation on the website, but after removing it gives me another error 
`error: cannot find symbol
        void onConsumeFinished(String token, @BillingResponse int result);
                                              ^
  symbol:   class BillingResponse
  location: interface BillingUpdatesListener
`

I'm using billing library version 1.2, does that conflicts with Qonoverions

**Comment by ArtemyGlukhov** [comment]
Hi! I will try to figure it out and give an answer during the day. Thanks

**Comment by ArtemyGlukhov** [comment]
Good day. Indeed, the problem is that your version of BillingClient is different from the version of BillingClient that is used inside the Qonversion SDK. The conflict occurs because the method signature of the old version of BillingClient is different from the method signature in the new version. I think that in your case, the easiest way is to raise the version of BillingClient to the current version 2.2 in your project. This will solve the problem of version conflict, and it will also be more correct in terms of the consistency of data sent to the SDK.

**Comment by ArtemyGlukhov** [comment]
Good afternoon, please tell me, is your problem still relevant? May i close issue?
