### ISSUE TITLE
Crash during Qonversion.initialize in FacebookAttribution

### ISSUE THREAD

**Issue by avalanchas** [qonversion/android-sdk#442]
# Description
We're currently seeing a couple hundred crashes per week (of some 100k users) during the Qonversion SDK `initialize`. 
```
Fatal Exception: java.lang.RuntimeException: Unable to create application de.radio.android.AppApplication: java.lang.IllegalArgumentException: java.lang.NoSuchMethodException: <init> [class X.0Y8]
       ...
Caused by java.lang.IllegalArgumentException: java.lang.NoSuchMethodException: <init> [class X.0Y8]
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
       at android.content.ContentProviderProxy.query(ContentProviderProxy.java:418)
       ...
       at com.qonversion.android.sdk.internal.FacebookAttribution.getAttributionId(FacebookAttribution.kt:11)
       at com.qonversion.android.sdk.internal.QUserPropertiesManager.sendFacebookAttribution(QUserPropertiesManager.kt:55)
       at com.qonversion.android.sdk.internal.QonversionInternal.<init>(QonversionInternal.kt:81)
       at com.qonversion.android.sdk.Qonversion$Companion.initialize(Qonversion.kt:61)
       at de.radio.android.tracking.billing.BillableApplication.onCreate(BillableApplication.kt:19)
```

# How to reproduce
Unknown for now, I have tested on a device with Facebook app installed and one without

# Devices, Versions
- Suspiciously, we're currently only seeing this on Huawei phones and some other minor brands. The huge majority of our userbase is on Samsung and there are 0 crashes on Samsung in Firebase Crashlytics right now. So this seems to be something device-specific 
<img src="https://user-images.githubusercontent.com/6008266/214008559-6b3ed93d-6f4c-4a94-804d-9215412fda96.png" width="400">

- **Only Android 8** seemingly
- Qonversion SDK: 4.0.0
- Android target and compile SDK: 33

**Comment by suriksarkisyan** [comment]
Hi, @avalanchas 
Thanks for contacting us. I'll try to understand and reproduce the problem and come back ASAP.

**Comment by suriksarkisyan** [comment]
Hi, @avalanchas 
Hi again, @dmitriev-alexey 
Happy to say that [4.1.2](https://github.com/qonversion/android-sdk/releases/tag/4.1.2) has been published. As you said, the problem looks device-specific, so it's hard to reproduce, but I hope the fix we made will help.
