### ISSUE TITLE
NumberFormatException on subscription

### ISSUE THREAD

**Issue by rlinoz** [qonversion/android-sdk#56]
After implementing the library and setting up a subscription test I am getting a NumberFormatException:

```
    java.lang.NumberFormatException: For input string: "52W1"
        at java.lang.Integer.parseInt(Integer.java:615)
        at java.lang.Integer.parseInt(Integer.java:650)
        at com.qonversion.android.sdk.converter.GooglePurchaseConverter.getUnitsCountFromPeriod(GooglePurchaseConverter.kt:3)
        at com.qonversion.android.sdk.converter.GooglePurchaseConverter.convert(GooglePurchaseConverter.kt:38)
        at com.qonversion.android.sdk.converter.GooglePurchaseConverter.convert(GooglePurchaseConverter.kt:1)
        at com.qonversion.android.sdk.QProductCenterManager.purchase(QProductCenterManager.kt:1)
        at com.qonversion.android.sdk.QProductCenterManager.handlePurchases(QProductCenterManager.kt:5)
        at com.qonversion.android.sdk.QProductCenterManager.access$handlePurchases(QProductCenterManager.kt:1)
        at com.qonversion.android.sdk.QProductCenterManager$getPurchasesListener$1.onPurchasesCompleted(QProductCenterManager.kt:1)
        at com.qonversion.android.sdk.billing.QonversionBillingService.onPurchasesUpdated(QonversionBillingService.kt:3)
        at h0.b.a.a.f0.onReceiveResult(com.android.billingclient:billing@@3.0.0:12)
        at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8125)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

Library version: 2.0.1
Android version: 10

**Comment by suriksarkisyan** [comment]
Hi, @rlinoz 
Thank you for the report.
We will fix it ASAP.
I am almost sure on Monday you can be able to update on the new version with the fix

**Comment by suriksarkisyan** [comment]
Hi again, @rlinoz 
Can you please provide some info about your Subscription configuration?
Looks like you receiving SkuDetails `subscriptionPeriod` in format "52W1" , which means 1 year period.
As [Google Documentation](https://developer.android.com/reference/com/android/billingclient/api/SkuDetails#getintroductorypriceperiod) said, 1 year period should be in format "P1Y", as ISO 8601 declaring.
I just can not find how to configure subscription to get period like "52W1". It is contrary to the documentation.

**Comment by rlinoz** [comment]
Hi @suriksarkisyan 

This is my subscription information, it is just a test subscription:

![image](https://user-images.githubusercontent.com/5201282/99962945-c8e4f500-2d6f-11eb-8c98-423bc025c33f.png)

**Comment by suriksarkisyan** [comment]
Thank you, @rlinoz 
We finally got it. We will fix it as soon as possible.
For now you can continue using and testing our SDK. You just need to change trial period from 365 to 3 days for example, and reset Google play cache

**Comment by suriksarkisyan** [comment]
Hi again, @rlinoz 
Issue is fixed https://github.com/qonversion/android-sdk/pull/64
Will be released today. I'll additionally notify

**Comment by suriksarkisyan** [comment]
Hi, @rlinoz 
[New release is available](https://github.com/qonversion/android-sdk/releases/tag/2.0.2)
You can update SDK version to 2.0.2
Thank you again! 🤜🤛
